name: Prisma Cloud Docker Image Scan
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Docker-Image-Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to Azure Registry
      - name: ACR login
        uses: azure/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      # Build Docker image
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: kjimages/myubuntu:${{ github.run_number }}

      # Runs Docker image scan
      - name: Docker Image Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_ACCESS_KEY_ID }}
          pcc_pass: ${{ secrets.PCC_SECRET_ACCESS_KEY }}
          image_name: kjimages/myubuntu:${{ github.run_number }}

      # Runs twistcli sandbox
      - name: Docker Image Sandbox Scan
        run: |
          curl -k -O -u $(PCC_ACCESS_KEY):$(PCC_SECRET_KEY) $(PCC_URL)/api/v1/util/twistcli;
           chmod a+x twistcli;

          sudo ./twistcli sandbox --address ${{ secrets.PCC_CONSOLE_URL }} --user ${{ secrets.PCC_ACCESS_KEY_ID }} --password ${{ secrets.PCC_SECRET_ACCESS_KEY }} --analysis-duration 5m kjimages/myubuntu:${{ github.run_number }}

# Push Image to registry if all the steps pass
      - name: Docker Push
        run: |
          docker push kjimages/myubuntu:${{ github.run_number }}
